### ISSUE TITLE
Angular 11 brand-new project issues

### ISSUE THREAD

**Issue by TheNemus** [danguilherme/ng-cli-pug-loader#38] opened 2020-11-17 14:09 UTC
I just created a brand-new angular project with

`ng new my-app`

The app runs without problems. Then I add the schematics:

`ng add ng-cli-pug-loader`

this is what I got back:

```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
CLI's Webpack config was not found. Try running `npm install` before running this tool.
```

I then run npm i as suggested, then the schematics:

```
Skipping installation: Package already installed
CLI's Webpack config was not found. Try running `npm install` before running this tool.
```

If I try to run the app with pug inside, I get some errors in console:

```
Error: Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
| style.
>   :host {
|   font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
|   font-size: 14px;
```

While the app works fine in browser.
What does those issues mean? How can I avoid them?

**Comment by ChickenRunVN** [comment] 2020-11-17 15:22
Please check this error #37, maybe this can help you.

**Comment by lxandrexl** [comment] 2020-11-18 13:13
new angular-devkit not include common.js 
we need change config in ng-add-pug-loader,js

**Comment by ChickenRunVN** [comment] 2020-11-18 13:29
> new angular-devkit not include common.js
> we need change config in ng-add-pug-loader,js

@lxandrexl The *common.js* file only move location, you can check #37 for more detail. Here is the new location:

```json
const commonCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js';

const typescriptCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/typescript.js';
```

**Comment by TheNemus** [comment] 2020-11-23 12:13
> > new angular-devkit not include common.js
> > we need change config in ng-add-pug-loader,js
> 
> @lxandrexl The `common.js` file only move location, you can check #37 for more detail. Here is the new location:
> 
> ```json
> const commonCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js';
> 
> const typescriptCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/typescript.js';
> ```

after trying to install the schemtics I've got no `ng-add-pug-loader,js` in my  project

**Comment by ChickenRunVN** [comment] 2020-11-23 14:14
> after trying to install the schematics I've got no `ng-add-pug-loader.js` in my project, maybe because the schematics itself failed

Hi @TheNemus , could you please commit your repository or guide me try to reproduce it step-by-step so I can take a look at it?

**Comment by TheNemus** [comment] 2020-11-23 15:15
> > after trying to install the schematics I've got no `ng-add-pug-loader.js` in my project, maybe because the schematics itself failed
> 
> Hi @TheNemus , could you please commit your repository or guide me try to reproduce it step-by-step so I can take a look at it?

sure. Upgrade your ng CLI to 11.0.x, then:

`ng new my-app`
`ng add ng-cli-pug-loader`

that's all

**Comment by ChickenRunVN** [comment] 2020-11-23 16:39
> sure. Upgrade your ng CLI to 11.0.x, then:
> 
> `ng new my-app`
> `ng add ng-cli-pug-loader`
> 
> that's all

Well, I have tried and found the problem with the detail as below:

- When you take a look at [the source file](https://github.com/danguilherme/ng-cli-pug-loader/blob/master/src/schematics/ng-add/index.ts) of this project, you can see
```json
const TARGET_COMMON_CONFIG_PATH = 'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js';
const TARGET_TYPESCRIPT_CONFIG_PATH = 'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js';
const NG_ADD_PUG_LOADER_SCRIPT_NAME = 'ng-add-pug-loader.js';

....

if (!commonConfigFile || !typescriptConfigFile)
  return throwError(new Error(`CLI's Webpack config was not found. Try running \`npm install\` before running this tool.`));
```
which will cause the error because the path for `common.js` and `typescript.js` has been changed, and that means you will not able to create a new project using `ng add ng-cli-pug-loader` command. The Author @danguilherme of this project hadn't been updated for a while so I think we won't have a new version to fix this soon.

- So, here is the way to work around and make your new project work with Angular 11:

1. Init new project with `ng new <your app name>` command.
2. Navigate to your new project folder.
3. Instead of using `ng add ng-cli-pug-loader`, you will have to install project dependency and script for pug manually. 
- First, install dependency with this command `npm install apply-loader@~2.0.0 pug-loader@~2.4.0 pug@~2.0.3 --save-dev`
- Create new script file `ng-add-pug-loader.js` in your project. You can find the initial for the file content [here](https://github.com/danguilherme/ng-cli-pug-loader/blob/master/src/files/ng-add-pug-loader.js).
- Open the file, find and replace the content for some variables as below:
```json
const commonCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js';
const pugRules = '{test:/\\.(pug|jade)$/,exclude:/\\.(include|partial)\\.(pug|jade)$/,use:[{loader:"apply-loader" },{loader:"pug-loader"}]},{test:/\\.(include|partial)\\.(pug|jade)$/,loader:"pug-loader"},';
const typescriptCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/typescript.js';
``` 
- Open your `package.json`, add `"postinstall": "node ./ng-add-pug-loader.js"` in the `scripts` section.
4. Run `npm i` command.

I have created a sample for you to check if needed, you can find it [here](https://github.com/ChickenRunVN/angular-11-pug-loader-sample). Hope that will help to solve your problem. Happy coding!

**Comment by SlateDave** [comment] 2021-01-29 18:17
What happens next?

**Comment by mp3por** [comment] 2021-06-16 13:11
Sooo ... did we lose this project ?

**Comment by guilmarc** [comment] 2021-11-10 11:32
I can't believe this project has been abandoned.  Any other way of using .pug file with Angular ?

**Comment by lekhmanrus** [comment] 2021-12-07 17:08
@guilmarc,  [Angular Pug Builders](https://github.com/lekhmanrus/ngx-pug-builders) - it could be used for Angular >=v12. It uses `@angular-devkit/build-angular` native builders as a dependency and extends them with webpack pug rules.

To use it with the current Angular version just run:
```sh
  ng add ngx-pug-builders
```
or for Angular 12:
```sh
  ng add ngx-pug-builders@12
```

See details [here](https://github.com/lekhmanrus/ngx-pug-builders).

**Comment by eshell** [comment] 2022-01-15 00:50
@ChickenRunVN 

I've been screwing around with this for a while, but found out what my problem was. I just had to fix one little thing in your ng-add-pug-loader.js script for it to work for me.  angular v13.1.3 / windows 11

node/npm are at the latest versions as of the date of this post.

 ```json
 const typescriptCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/configs/typescript.js';
 ```
needs to be 
```json
 const typescriptCliConfig = 'node_modules/@angular-devkit/build-angular/src/webpack/plugins/typescript.js';
```

the file in your post didn't exist for me.

**Comment by jrgleason** [comment] 2023-11-19 17:12
@lekhmanrus Looks like that project is abandoned now too? I see that it has not been released in a while an no 17 support?

**Comment by jrgleason** [comment] 2023-11-19 17:13
NM now I see this so it sounds like it will be some time before 17 support

https://github.com/lekhmanrus/ngx-pug-builders/issues/10

**Comment by lekhmanrus** [comment] 2023-11-21 19:32
Hi @jrgleason, new version just released. Btw, see [currently supported builders](https://github.com/lekhmanrus/ngx-pug-builders#builders-support).

**Comment by danguilherme** [comment] 2023-11-21 22:04
Hey there @lekhmanrus, as this repo is not maintained I'll link to your project in the README if that's alright.

**Comment by lekhmanrus** [comment] 2023-11-21 23:17
Hi @danguilherme, sure, thanks. 🙂

**Comment by danguilherme** [comment] 2023-11-22 00:00
This project is no longer maintained. Check out [ngx-pug-builders](https://github.com/lekhmanrus/ngx-pug-builders) to add support to pug files to your Angular project.

**Closed by danguilherme** 2023-11-22 00:00 UTC
